# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Hjemmeside titel
logo: images/mig2.jpg
#description: text below image
#show_downloads: true
theme: al-folio



