# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Hjemmeside titel
logo: images/vand.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal




