# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Monique Kvistholm
logo: /assets/img/vand.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal

