# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Hjemmeside titel
logo: images/vand.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal


repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md


